Fix Conditional Typing in useSWRMutation to Allow Optional ExtraArg Without Explicitly Passing Undefined
vercel/swr pull request #2666
Opened 2023-06-13 01:19 UTC by saengmotmi

This PR contains the fixes for the issue: https://github.com/vercel/swr/issues/2665.

This is my first contribution to SWR. Thank you in advance :)

2023-06-13 06:50 UTC, promer94 requested changes
I think the correct way to fix this problem is to have a new `TriggerWithOptionsArgs` type. 

So you can improve the type inference implementation here.
https://github.com/vercel/swr/blob/7badbb9d428d2ac48873b3a3f11d54e7cec0c7cf/mutation/types.ts#L142-L144

`ExtraArg = never`  ->  `TriggerWithoutArgs`
`ExtraArg = number | undefined` -> `TriggerWithOptionsArgs`
`ExtraArg = number` -> `TriggerWithArgs`


Also. You need to add a new test for optional `arg`

2023-06-13 06:50 UTC, promer94 commented on mutation/types.ts
> +    extraArgument?: ExtraArg,
I don't think this is the right fix. And it breaks the type validation for required `args`

What we expect here are 

For required `arg`

```tsx
const { trigger, reset, data, error } = useSWRMutation(
    '/api/user',
    (_, opts: { arg: number }) => String(opts.arg)
)
// should throw error, but your change breaks this.
trigger()
// pass type validation
trigger(1)
```

For optional `arg`

```tsx
const { trigger, reset, data, error } = useSWRMutation(
    '/api/user',
    (_, opts: { arg?: number }) => String(opts.arg)
)
// pass type validation
trigger()
// pass type validation
trigger(1)
```

2023-06-13 06:50 UTC, promer94 commented on test/type/trigger.ts
> -    // @ts-expect-error `arg` should be 'foo'
This part is actually relevant, you shouldn't remove them

2023-06-18 06:24 UTC, saengmotmi commented
@promer94 Oh, I see. I had made incorrect changes. I understand your suggestion. I've made changes according to your suggestion.

I introduced a new `TriggerWithOptionsArgs` type and made the appropriate adjustments for type inference. I have also added a new test for the optional argument.

Please review my latest changes and let me know if there's anything else I need to address.

2023-06-18 09:05 UTC, promer94 approved these changes
Thanks!

2023-06-18 09:06 UTC, merged